from .global_variables import Global
CART = 1
DELIVERY_TYPE = 2
BOXBERRY = 3
CREDENTIALS_N=4
CREDENTIALS_SN=5
CREDENTIALS_POSTINDEX=6
CREDENTIALS_PHONE=7
CREDENTIALS_EMAIL=8
CREDENTIALS_CHECK=9
ADMIN_CREDS=10
global_state = {}
admin_list = []